export default [
	{
		userName: 'emily',
		foreName: 'Emily',
		lastName: 'Watson',
		bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam efficitur, justo dictum lacinia sollicitudin, orci ipsum',
		imageUrl: 'http://c6.staticflickr.com/4/3785/12598293093_665bd91752_h.jpg',
		interestedIn: 'Lunch',
		location: 'Miami',
		hobbies: 'Playing chess',
		discussionTopic: 'Javascript',
		meetingTime : '13:00'
	},
	{
		userName: 'linda',
		foreName: 'Linda',
		lastName: 'Haggarthy',
		bio: 'Pellentesque vitae quam maximus, vestibulum erat vitae, efficitur tortor. Nam non elementum dolor.',
		imageUrl: 'http://c2.staticflickr.com/7/6031/6263774505_9e0a7df01e_b.jpg',
		interestedIn: 'Group eat',
		location: 'England',
		hobbies: 'Beach Vollyball',
		discussionTopic: 'React Native',
		meetingTime : '14:00'
	},
	{
		userName: 'june',
		foreName: 'June',
		lastName: 'Haines',
		bio: 'Morbi ac diam sit amet nisl luctus mattis. Aliquam erat volutpat. Vivamus ac ante eu nisi eleifend molestie a at tortor.',
		imageUrl: 'http://c1.staticflickr.com/4/3754/13888965536_76a7cd9901_c.jpg',
		interestedIn: 'Lunch',
		location: 'Ukraine',
		hobbies: 'Reading Novels',
		discussionTopic: 'Reactive Java',
		meetingTime : '13:00'
	},
	{
		userName: 'karry',
		foreName: 'Karry',
		lastName: 'Gracia',
		bio: 'Curabitur fermentum malesuada ex. Phasellus finibus tortor sapien, at pellentesque sem convallis vitae.',
		imageUrl: 'http://c7.staticflickr.com/8/7255/7453525934_5cd57823f3_z.jpg',
		interestedIn: 'Lunch',
		location: 'Russia',
		hobbies: 'Politics',
		discussionTopic: '.Net Development',
		meetingTime : '12:00PM'
	},
	{
		userName: 'adam',
		foreName: 'Adam',
		lastName: 'Wheelright',
		bio: 'Pellentesque tristique porta ligula a rhoncus. Vestibulum pellentesque libero vel elit interdum, a ultrices est mattis.',
		imageUrl: 'http://c4.staticflickr.com/4/3817/13339018395_e6dea96f88_c.jpg',
		interestedIn: 'Lunch',
		location: 'England',
		hobbies: 'Playing chess',
		discussionTopic: 'Javascript',
		meetingTime : '13:00PM'
	},
	{
		userName: 'johnathan',
		foreName: 'Jonathan',
		lastName: 'Moore',
		bio: 'Vestibulum venenatis, enim eget placerat mollis, sem nisl ultricies urna, vel pretium orci urna ut quam.',
		imageUrl: 'http://c8.staticflickr.com/4/3801/13339165783_51eb6f4deb_c.jpg',
		interestedIn: 'Lunch',
		location: 'United States',
		hobbies: 'Playing chess',
		discussionTopic: 'Javascript',
		meetingTime : '13:00PM'
	},
	{
		userName: 'andrew',
		foreName: 'Andrew',
		lastName: 'Gore',
		bio: 'Praesent eget accumsan eros. Praesent condimentum rutrum dui, id tempus libero.',
		imageUrl: 'http://c5.staticflickr.com/6/5575/15000743876_7e09a66252_b.jpg',
		interestedIn: 'Lunch',
		location: 'Germany',
		hobbies: 'Playing chess',
		discussionTopic: 'Javascript',
		meetingTime : '13:00PM'
	},
	{
		userName: 'dave',
		foreName: 'David',
		lastName: 'Murphy',
		bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam efficitur, justo dictum lacinia sollicitudin, orci ipsum',
		imageUrl: 'http://c5.staticflickr.com/9/8210/8224293788_3979aaeedf_c.jpg',
		interestedIn: 'Lunch',
		location: 'Miami',
		hobbies: 'Playing chess',
		discussionTopic: 'Javascript',
		meetingTime : '13:00'
	},
	{
		userName: 'jose',
		foreName: 'Jose',
		lastName: 'Martin',
		bio: 'Pellentesque vitae quam maximus, vestibulum erat vitae, efficitur tortor. Nam non elementum dolor.',
		imageUrl: 'http://c7.staticflickr.com/6/5224/5615892830_c87d303ec4_b.jpg',
		interestedIn: 'Group eat',
		location: 'England',
		hobbies: 'Beach Vollyball',
		discussionTopic: 'React Native',
		meetingTime : '14:00'
	},
	{
		userName: 'rita',
		foreName: 'Rita',
		lastName: 'Watson',
		bio: 'Morbi ac diam sit amet nisl luctus mattis. Aliquam erat volutpat. Vivamus ac ante eu nisi eleifend molestie a at tortor.',
		imageUrl: 'http://c8.staticflickr.com/4/3753/10178701815_92c698a8cd_c.jpg',
		interestedIn: 'Lunch',
		location: 'Ukraine',
		hobbies: 'Reading Novels',
		discussionTopic: 'Reactive Java',
		meetingTime : '13:00'
	},
	{
		userName: 'fairuza',
		foreName: 'Fairuza',
		lastName: 'Morgan',
		bio: 'Curabitur fermentum malesuada ex. Phasellus finibus tortor sapien, at pellentesque sem convallis vitae.',
		imageUrl: 'http://c7.staticflickr.com/6/5007/13980214766_141d57c8ea_b.jpg',
		interestedIn: 'Lunch',
		location: 'Russia',
		hobbies: 'Politics',
		discussionTopic: '.Net Development',
		meetingTime : '12:00PM'
	},
	{
		userName: 'wandy',
		foreName: 'Wandy',
		lastName: 'Middleton',
		bio: 'Pellentesque tristique porta ligula a rhoncus. Vestibulum pellentesque libero vel elit interdum, a ultrices est mattis.',
		imageUrl: 'http://c3.staticflickr.com/4/3766/9573831826_9ebabdf3bd_k.jpg',
		interestedIn: 'Lunch',
		location: 'England',
		hobbies: 'Playing chess',
		discussionTopic: 'Javascript',
		meetingTime : '13:00PM'
	},
	{
		userName: 'Riya',
		foreName: 'Malik',
		lastName: 'Moore',
		bio: 'Vestibulum venenatis, enim eget placerat mollis, sem nisl ultricies urna, vel pretium orci urna ut quam.',
		imageUrl: 'http://c5.staticflickr.com/4/3717/9726755668_b6721e00a0_k.jpg',
		interestedIn: 'Lunch',
		location: 'United States',
		hobbies: 'Playing chess',
		discussionTopic: 'Javascript',
		meetingTime : '13:00PM'
	},
	{
		userName: 'andrew',
		foreName: 'Andrew',
		lastName: 'William',
		bio: 'Praesent eget accumsan eros. Praesent condimentum rutrum dui, id tempus libero.',
		imageUrl: 'http://c8.staticflickr.com/8/7355/14184428351_0c6995c88f_k.jpg',
		interestedIn: 'Lunch',
		location: 'Germany',
		hobbies: 'Playing chess',
		discussionTopic: 'Javascript',
		meetingTime : '13:00PM'
	},
	{
		userName: 'abraham',
		foreName: 'Abraham',
		lastName: 'Watson',
		bio: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam efficitur, justo dictum lacinia sollicitudin, orci ipsum',
		imageUrl: 'http://c7.staticflickr.com/9/8574/16618641622_058dd4c0ed_k.jpg',
		interestedIn: 'Lunch',
		location: 'Miami',
		hobbies: 'Playing chess',
		discussionTopic: 'Javascript',
		meetingTime : '13:00'
	},
	{
		userName: 'lucy',
		foreName: 'Lucy',
		lastName: 'Kavanog',
		bio: 'Pellentesque vitae quam maximus, vestibulum erat vitae, efficitur tortor. Nam non elementum dolor.',
		imageUrl: 'http://c2.staticflickr.com/5/4100/4997575585_42d7d48ff3_b.jpg',
		interestedIn: 'Group eat',
		location: 'England',
		hobbies: 'Beach Vollyball',
		discussionTopic: 'React Native',
		meetingTime : '14:00'
	},
	{
		userName: 'june',
		foreName: 'June',
		lastName: 'Haines',
		bio: 'Morbi ac diam sit amet nisl luctus mattis. Aliquam erat volutpat. Vivamus ac ante eu nisi eleifend molestie a at tortor.',
		imageUrl: 'http://c1.staticflickr.com/4/3754/13888965536_76a7cd9901_c.jpg',
		interestedIn: 'Lunch',
		location: 'Ukraine',
		hobbies: 'Reading Novels',
		discussionTopic: 'Reactive Java',
		meetingTime : '13:00'
	},
	{
		userName: 'rubina',
		foreName: 'Rubina',
		lastName: 'Chaddha',
		bio: 'Curabitur fermentum malesuada ex. Phasellus finibus tortor sapien, at pellentesque sem convallis vitae.',
		imageUrl: 'http://c2.staticflickr.com/5/4043/4683505897_c004d688f7_b.jpg',
		interestedIn: 'Lunch',
		location: 'Russia',
		hobbies: 'Politics',
		discussionTopic: '.Net Development',
		meetingTime : '12:00PM'
	},
	{
		userName: 'adam',
		foreName: 'Adam',
		lastName: 'Wheelright',
		bio: 'Pellentesque tristique porta ligula a rhoncus. Vestibulum pellentesque libero vel elit interdum, a ultrices est mattis.',
		imageUrl: 'http://c4.staticflickr.com/5/4004/4683495259_813b8eed0c_b.jpg',
		interestedIn: 'Lunch',
		location: 'England',
		hobbies: 'Playing chess',
		discussionTopic: 'Javascript',
		meetingTime : '13:00PM'
	},
	{
		userName: 'ruth',
		foreName: 'Ruth',
		lastName: 'Moore',
		bio: 'Vestibulum venenatis, enim eget placerat mollis, sem nisl ultricies urna, vel pretium orci urna ut quam.',
		imageUrl: 'http://c6.staticflickr.com/2/1338/5116201789_570b05395e_b.jpg',
		interestedIn: 'Lunch',
		location: 'United States',
		hobbies: 'Playing chess',
		discussionTopic: 'Javascript',
		meetingTime : '13:00PM'
	},
	{
		userName: 'rebecca',
		foreName: 'Rebecca',
		lastName: 'Wyer',
		bio: 'Praesent eget accumsan eros. Praesent condimentum rutrum dui, id tempus libero.',
		imageUrl: 'http://c4.staticflickr.com/3/2941/15423964531_aab2371a61_h.jpg',
		interestedIn: 'Lunch',
		location: 'Germany',
		hobbies: 'Playing chess',
		discussionTopic: 'Javascript',
		meetingTime : '13:00PM'
	}
]